/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "uhtwwxtazwqnlbejhprl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVodHd3eHRhendxbmxiZWpocHJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNDQxMTQsImV4cCI6MjA3ODYyMDExNH0.sS-a900AR_ZWpaWCK1qN2Zvt0pIUaxl_e-g-fiLI60s"