import { afterEach, describe, expect, it, vi } from 'vitest';
import {
  getApiBaseUrl,
  getPayuniPaymentUrl,
  getPublicAppUrl,
  getSupabaseAnonKey,
  getSupabaseUrl,
} from './config';
import { projectId, publicAnonKey } from './utils/supabase/info';

afterEach(() => {
  vi.unstubAllEnvs();
});

describe('getPayuniPaymentUrl（fail-fast，不得有正式金流預設）', () => {
  it('未設環境變數時擲錯，而非默默退回寫死的正式網址', () => {
    vi.stubEnv('VITE_PAYUNI_PAYMENT_URL', '');
    expect(() => getPayuniPaymentUrl()).toThrow(/VITE_PAYUNI_PAYMENT_URL/);
  });

  it('有設定時回傳該值', () => {
    vi.stubEnv('VITE_PAYUNI_PAYMENT_URL', 'https://staging.example.com/pay');
    expect(getPayuniPaymentUrl()).toBe('https://staging.example.com/pay');
  });
});

describe('Supabase 設定（env 覆蓋，否則退回 autogenerated info.tsx）', () => {
  it('未設時退回由 project id 組出的 URL', () => {
    vi.stubEnv('VITE_SUPABASE_URL', '');
    vi.stubEnv('VITE_SUPABASE_PROJECT_ID', '');
    expect(getSupabaseUrl()).toBe(`https://${projectId}.supabase.co`);
    expect(getSupabaseAnonKey()).toBe(publicAnonKey);
  });

  it('VITE_SUPABASE_URL 可覆蓋以指向 staging', () => {
    vi.stubEnv('VITE_SUPABASE_URL', 'https://staging.supabase.co');
    expect(getSupabaseUrl()).toBe('https://staging.supabase.co');
    expect(getApiBaseUrl()).toBe('https://staging.supabase.co/functions/v1/api');
  });
});

describe('getPublicAppUrl', () => {
  it('去掉尾端斜線', () => {
    vi.stubEnv('VITE_PUBLIC_APP_URL', 'https://uknow.tw/');
    expect(getPublicAppUrl()).toBe('https://uknow.tw');
  });

  it('未設時回 undefined（由呼叫端退回站台 origin）', () => {
    vi.stubEnv('VITE_PUBLIC_APP_URL', '');
    expect(getPublicAppUrl()).toBeUndefined();
  });
});
