// 前端執行環境設定的單一入口。
//
// 為什麼集中：原本 projectId/anonKey 寫死在 utils/supabase/info.tsx、PayUni 網址
// 以「|| 正式網址」的形式埋在 PaymentCheckout 裡——後者最危險：任何沒設環境變數
// 的環境（預覽/測試）會「默默打到正式金流」。集中後：可用環境變數指向 staging，
// 且必要值缺失時 fail-fast，而不是退回一個危險的預設。
//
// 注意：import.meta.env 的值是 Vite 於 build 時內聯的字串。讀取一律在函式/取值
// 當下進行，方便 vitest 以 vi.stubEnv 測試。

import { projectId as generatedProjectId, publicAnonKey as generatedAnonKey } from './utils/supabase/info';

function readEnv(key: string): string | undefined {
  const raw = (import.meta.env as Record<string, string | undefined> | undefined)?.[key];
  const trimmed = raw?.trim();
  return trimmed ? trimmed : undefined;
}

/**
 * Supabase 專案 id。anon key 屬公開金鑰、info.tsx 為 autogenerated 的預設；
 * 設定 VITE_SUPABASE_PROJECT_ID 可覆蓋以指向不同專案/環境。
 */
export function getSupabaseProjectId(): string {
  return readEnv('VITE_SUPABASE_PROJECT_ID') ?? generatedProjectId;
}

/** Supabase 站台 URL（可用 VITE_SUPABASE_URL 直接覆蓋，否則由 project id 組出）。 */
export function getSupabaseUrl(): string {
  return readEnv('VITE_SUPABASE_URL') ?? `https://${getSupabaseProjectId()}.supabase.co`;
}

/** Supabase anon（public）key；可用 VITE_SUPABASE_ANON_KEY 覆蓋。 */
export function getSupabaseAnonKey(): string {
  return readEnv('VITE_SUPABASE_ANON_KEY') ?? generatedAnonKey;
}

/** 後端 Edge Function API 基底：`https://<project>.supabase.co/functions/v1/api`。 */
export function getApiBaseUrl(): string {
  return `${getSupabaseUrl()}/functions/v1/api`;
}

/**
 * PayUni 定期定額付款網址。
 *
 * 刻意「不提供預設」：這是正式金流端點，缺值時 fail-fast 擲錯，杜絕沒設環境變數
 * 的環境默默把使用者導去正式金流。部署環境務必設定 VITE_PAYUNI_PAYMENT_URL
 * （見 .env.example）。
 */
export function getPayuniPaymentUrl(): string {
  const url = readEnv('VITE_PAYUNI_PAYMENT_URL');
  if (!url) {
    throw new Error(
      '[config] 缺少 VITE_PAYUNI_PAYMENT_URL —— 付款網址必須由環境變數提供，' +
        '不得使用寫死的正式金流預設值。請於部署環境設定此變數。',
    );
  }
  return url;
}

/**
 * 對外分享連結用的網域來源；可用 VITE_PUBLIC_APP_URL 於正式環境釘死，
 * 未設時由呼叫端退回目前站台 origin（預覽環境也能產生可用連結）。
 */
export function getPublicAppUrl(): string | undefined {
  return readEnv('VITE_PUBLIC_APP_URL')?.replace(/\/$/, '');
}
